### PR TITLE
Added Links and Screenshots for API impressions

### PR DESCRIPTION
**Pull request by Sc0rpi0n101**
ping @Nishchit14 @vipulgupta2048 

Is there anything else to be done here? Missed a screenshot or link somewhere?

Also, how should I caption these?

### CODE REVIEW

**Comment by Sc0rpi0n101** [comment]
>     * The build is failing, fix that. I think there is a closing tag missing.

The build log has the same error for the last 3 PRs, so I' not sure where it's from.

>     * Not sure why I can't see the images on GitHub with rich diff, can you confirm the paths are correct.
Can you tell me which ones you can't see? I could see most of them.

**Comment by Nishchit14** [comment]
Awesome @Sc0rpi0n101 and @vipulgupta2048 !!

I am struggling with the Link issue after merging all pending PR, Due to it, the build is being failed all the time. I'll fix it soon.

**Comment by Nishchit14** [comment]
The `Link` issue has been solved, so once @vipulgupta2048 approve this PR, I'll merge it :)

**Comment by Nishchit14** [comment]
@vipulgupta2048 this. the build will always fail because this PR is being created fork instead of other branches.

**Comment by vipulgupta2048** [comment]
Right, this is something I mentioned before in terms of scalability @Nishchit14 because once the public contributors starts increasing not all of them can be invited to the organisation and be given push access to make new branches and make changes on them.

Most people don't even think about it because the best practice in open-source is to make a fork of the project and then make changes. Hence, everyone will be doing that. I think we would need to find a workaround for this.

**Pull request merged**
